name: rhel-9-base

on:
  push:
    branches:
      - main
    paths:
      - "packer/**/*rhel*"
      - ".github/workflows/rhel-9-base.yml"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use variables
        run: |
          echo "subscription id : $ARM_SUBSCRIPTION_ID"
          echo "tenant id : $ARM_TENANT_ID"
          echo "client id : $ARM_CLIENT_ID"
          echo "client secret : $ARM_CLIENT_SECRET"
        env:
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ vars.ARM_CLIENT_SECRET }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest" # or latest

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/builds"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/builds"