name: rhel-9x-base

on:
  push:
    branches:
      - main
    paths:
      - "packer/**/*rhel*"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest" # or latest

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/builds"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/builds"