name: windows-2019-base

on:
  push:
    branches:
      - main
    paths:
      - "packer/**/*windows*"
  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest" # or latest

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/builds"

      - name: Run `packer validate`
        id: validate
        run: packer validate ./packer/builds/build_windows.pkr.hcl

      - name: Run `packer build`
        id: build
        run: |
          export HCP_CLIENT_ID=${{ secrets.AZURE_TENANT_ID }}
          export HCP_CLIENT_SECRET=${{ secrets.AZURE_SUBSCRIPTION_ID }}

          packer build \
          -var "azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}"" \
          -var "azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"" \
          -var "azure_client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -var "azure_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" ./packer/builds/build_windows.pkr.hcl